### ISSUE TITLE
index.js:30 Uncaught DOMException: Failed to execute 'createMediaStreamSource' on 'AudioContext': MediaStream has no audio track

### ISSUE THREAD

**Issue by tailoric** [VivaLaPanda/sympho-slots#1]
Error got thrown on Maria and Tsubasa's song with the following slot constellation: 
![image](https://user-images.githubusercontent.com/16943959/99901437-f91c8d00-2cb6-11eb-9cb6-8c26596e641c.png)
This happened after rerolling the slots from the Tsubasa, Chris and Hibiki song.

```
index.js:30 Uncaught DOMException: Failed to execute 'createMediaStreamSource' on 'AudioContext': MediaStream has no audio track
    at visualize (https://vivalapanda.moe/sympho-slots/index.js:30:33)
    at startVisualizer (https://vivalapanda.moe/sympho-slots/index.js:16:5)
    at https://vivalapanda.moe/sympho-slots/index.js:471:25
```

**Comment by tailoric** [comment]
Managed to get the same thing again this time everything worked tho
